- name: Install virtualenv, pip and python-dev
  package: name={{ item }} state=present
  with_items:
    - python-pip
    - "{{ python_dev_package_name }}"
    - "{{ virtualenv_package_name }}"

- name: Install C compiler tools (RHEL)
  yum: name="@Development tools" state=present
  when: ansible_distribution == 'CentOS'

- name: Install C compiler tools (Debian)
  package: name=build-essential state=present
  when: ansible_distribution != 'CentOS'

- name: Upgrade pip
  command: pip install --upgrade pip

- name: Install uWSGI
  pip: name=uwsgi state=present

- name: Create uWSGI vassal configuration directory
  file: path=/etc/uwsgi/vassals state=directory

- name: Create uWSGI service
  template: src=templates/uwsgi.service.j2 dest=/lib/systemd/system/uwsgi.service
  notify: Restart uwsgi

- name: Reload systemd services
  command: systemctl daemon-reload

- name: Enable and start uWSGI service
  service: name=uwsgi state=started enabled=yes
  ignore_errors: yes
