- name: Check if iptables directory exists
  stat: path=/etc/sysconfig/iptables
  register: iptables_dir

- name: Open TCP port for HTTP 80 (iptables)
  lineinfile: >
    dest=/etc/sysconfig/iptables
    regexp="^-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT"
    line="-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT"
    insertbefore="^-A INPUT -j REJECT --reject-with icmp-host-prohibited"
  when: iptables_dir.stat.islnk is defined
  notify:
    - Restart iptables

- name: Open TCP port for HTTP 443 (iptables)
  lineinfile: >
    dest=/etc/sysconfig/iptables
    regexp="^-A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT"
    line="-A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT"
    insertbefore="^-A INPUT -j REJECT --reject-with icmp-host-prohibited"
  when: iptables_dir.stat.islnk is defined
  notify:
    - Restart iptables

- name: Open TCP port for HTTP 80 (ip6tables)
  lineinfile: >
    dest=/etc/sysconfig/ip6tables
    regexp="^-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT"
    line="-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT"
    insertbefore="^-A INPUT -j REJECT --reject-with icmp6-adm-prohibited"
  when: iptables_dir.stat.islnk is defined
  notify:
    - Restart ip6tables

- name: Open TCP port for HTTP 443 (ip6tables)
  lineinfile: >
    dest=/etc/sysconfig/ip6tables
    regexp="^-A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT"
    line="-A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT"
    insertbefore="^-A INPUT -j REJECT --reject-with icmp6-adm-prohibited"
  when: iptables_dir.stat.islnk is defined
  notify:
    - Restart ip6tables
